### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by jsalbr** [philschmid/fine-tune-GPT-2#1]
Hi Phil,

I just tried your GPT-2 notebook. It seems that the transformers API slightly changed, because I ran into an error:

TypeError: __init__() got an unexpected keyword argument 'prediction_loss_only'

The parameter of the Trainer prediction_loss_only=True seems to have moved to TrainingArguments. 
It would be great if you could update that notebook as the tutorial is really nice.

Best, Jens

P.S. Small world: I'm located in Nuremberg as well ;-) Maybe we could get in touch.

**Comment by philschmid** [comment]
Yep, the API probably has changed. I adjusted the notebook and pin a version for `transformers`
